### ISSUE TITLE
Comparison to hyperx

### ISSUE THREAD

**Issue by passcod** [straker/html-tagged-template#12]
What's the difference between this and [hyperx](https://github.com/substack/hyperx)? (Apart from the "proposal that this be a standard".)

**Comment by straker** [comment]
I guess looking over the internals of hyperx, the main differences would be that hyperx parses a DOM string character by character (since it has to do in in a virtual DOM environment like Node.js), whereas I just let the HTML parser of the browser do that for me, and this proposal also includes XSS prevention techniques to make DOM creation safer when using user generated content. 

Other than that, the interface is roughly the same (i.e. use a tagged template function to make the DOM), just a different implantation.
