### ISSUE TITLE
Easier boolean attributes

### ISSUE THREAD

**Issue by tabatkins** [straker/html-tagged-template#32]
From the usage example, it looks like boolean attributes currently have to be manually handled by outputting either their name or an empty string, using a ternary.

This is a bit clumsy. It would be a lot more aesthetically appealing if you could write something like:

```
const el = html`<video controls?={showControls} url={url}></video>`;
```

That is, if the attr name is followed by a `?=` operator, its value is checked as a boolean, and the attribute is either included or omitted accordingly.

(Any similar sort of syntax would work, of course.)

**Comment by straker** [comment]
I agree that conditional attributes using a ternary is a bit clumsy. The only concern I have is that doing `?=` or a similar syntax would be diverging from what is possible with `innerHTML`. Now I'm not saying that's a bad thing, it's just that I've been trying to figure out the [right balance](https://github.com/whatwg/dom/issues/150#issuecomment-324390296) between how to get this proposal moving forward and getting implementer interest and all [the different ways the same problem is being solved](https://github.com/whatwg/dom/issues/150#issuecomment-317908532).

Since you've been around the block a time or two getting proposals through the spec groups, at what level do you see this API falling under? Should it be something low level that mimics `innerHTML` like syntax but without the need of an outer element? Or would this be better as a higher level API, which means we should add features that break away from `innerHTML` but that add more conveniences for the developer?

**Comment by tabatkins** [comment]
Depends!  Both are valid approaches.

In particular, trying to piggyback on https://github.com/whatwg/html/issues/3052 might be useful; the implementors there want to be able to produce "trusted HTML" types, where you know for sure that what you're inserting isn't vulnerable to injection, and having a powerful built-in template to do that with can be useful. You don't want to go too far, but putting in just a few small conveniences might make it more attractive.  (Libraries will be able to produce these themselves, so they can handle more complicated/weird templating semantics on their own.)
